import { Base } from './base';
import { BaseFactory } from './base-factory';
import { Color } from './color';
// import { ColorMain1 } from './color-main1';
import { Compute } from './compute';
import { Converter } from './converter';
import { Culture } from './culture';
import { CMYK } from './models/cmyk';
import { HSL } from './models/hsl';
import { LAB } from './models/lab';
import { RGB } from './models/rgb';
import { XYZ } from './models/xyz';
import { Parser } from './parser';
// import { Mix } from './mix';
// import { Group } from './collections/group';
import { Relation } from './relation';
import { Web } from './web';

// export { ColorMain1 };
export { Relation };
export { Culture };
export { Compute };
export { Converter };
// export { Mix };
// export { Group };
export { Parser };
export { Web };
export { Base };
export { BaseFactory };
export { Color };
export { CMYK };
export { HSL };
export { LAB };
export { RGB };
export { XYZ };
